= Basic Types and Control Flow

Programs begin with data.
They then perform operations on that data over time.
This chapter introduces you to what data is in a proram, and how to control that time aspect.
After we have an overview of what data is, and how we can operate on it, we'll write a number guessing game.

:leveloffset: 2

include::01_types/00_textbook.adoc[]

include::02_control/00_textbook.adoc[]

include::02_control/00_tracing.adoc[]

include::03_hilo/00_textbook.adoc[]

== Wrap Up

Let's take a minute to appreciate what we've covered and accomplished!
We started with a code editor and a way to run a Python progam, but at the time it didn't do much more than print "Hello, world!".
Over the past chapter, we've learned about how computers represent data, taking just numbers and making them serve all sorts of different purposes.
We've looked at how to control the computer, making it branch and loop based on conditions.
We used that to write a program which converted our numbers to Roman numerals.
You wrote your (likely) first program! That did a real thing, that is useful!
(Ok... questionably useful, but the next programs will really be useful!)
Then we took that knowledge and wrote a jackpot game, that lets us test our skill at picking numbers.
Not content at the bare rules of the game, we added color, boxes, and maybe even a little animation to snazzy it up! Be proud of yourself, you are now a computer programmer!

****
*Recommended:* Take a detour through [Appendix 2: Source Control](../A02_source_control/README.md)
****

:leveloffset: 1