= Introduction to Objects

In this chapter, we take our understanding of programming as variables tracking
values over time and begin to add structure that will help us manage complexity
as our code grows. We use **functions** to manage the complexity of breaking out
executable pieces of code over time. Here, we start using **objects** to manage
the complexity of pieces of data with multiple facets. We begin to get an
understanding of these by building out a program which prints a desktop
calendar.

The second project takes us from using built-in objects to building out our own
objects. Returning to the trusty Rug Shop, **classes** will describe the data
of a rug, and **methods** will let us cut down yet again on the code needed to
keep all the rug types around. We will gain a large amount of flexibility in how
rugs are stored and priced, and can use this to quickly create many more types
of rugs.

The last section will take us back to video games. We'll build out a set of
classes which let us have a maze or labyrinth that our intrepid player must
navigate, collecting keys for locked doors before finding the treasure room.

:leveloffset: 2

include::01_calendar/00_textbook.adoc[]

include::02_rugs/00_textbook.adoc[]

include::03_maze/00_textbook.adoc[]

== Wrap Up: Objects, Classes, and Object Oriented Design

In this chapter, we've looked at bundling data into objects. This allows using
a single variable to track complex data, accessing pieces of the complex data
via its properties. We looked at built-in objects representing dates and times,
and used those to build a calendar that showes us the days in a month, holidays,
weekends, and days until some event.

We then explored using classes and inheritence to describe, create, and simplify
object handling. With the rugs functions we've been using, we created a class
for each type of rug. Each rug type was able to do its own calculations on its
own contained data sets. There was still some duplication, so we introduced the
idea of inheritance - letting one class provide foundational behavior, and
several variations of that behavior in subclasses. This let us have clear,
concise, contained code for each type of rug, and our input and output utilities
didn't need large amounts of special casing.

With the understanding of creating and using objects, we added a technique to
track objects, their properties, and their lifecycle in our program traces. ...

We ended the chapter building a maze game. This gave us more practice with
classes, but more importantly, we used it as a jumping point for talking about
object and program design. We saw how using classes and objects let us write
clear code which shows its intent.

These first three chapters have given us the basic building blocks of writing
computer programs. From here, we will look at techniques for building programs
that are larger and more difficult to understand at one time. These tools will
aid in developing these larger programs in a systematic and verifiable way.

:leveloffset: 1