= Introduction

Welcome to the Software Craftsmanship Rust Workbook.
This workbook will lead you through a variety of programming exercises in conjunction with the main
Software Craftsmanship book.
Programming is a skill, and like any other skill,
it takes practice to become truly profficient.
The exercises in this book range from "monkey-see-monkey-do" problems getting you used to typing exactly as a computer expects, to free-ranging ideas on programs you might be interested in writing for yourself.

You will want to complete every "MSMD" section exxctly as written.
Computers are not forgiving when it comes to what you type in your program, and these
exercises are a safe way to begin exploring the world of computer programming.
The exercises for each chapter build on the MSMD section, and are opportunities for you to apply what you've learned conceptually to a program.
You should make an attempt to complete all the exercises.
Finally, projects are larger scale ideas for programs that you would be able to write with the tools presented by that point in the main text.
The more you program, the better a programmer you'll be, but you'll probably want to pick and choose projects that interest you.

== Rust

https://rustup.rs[Rustup.rs]

=== cargo

Rust is a compiled language.
As such, before running a Rust souce file, you must first compile it into an executable program.
The program to run to compile the source file is called (gee, surprise) a compiler.
Rust uses a tool called `cargo` to manage all aspects of compiling, running, and testing programs.

== First Program

Let's write our first program.
Open your text editor (`code .`), and type the following:

=== src/main.rs

[,rust]
----
fn main() {
	println!("Hello, world!");
	println!("0x{:X} {} {:?}\n", 2 + 3, 10/7.0, 152 * 12.6);
}
----

Save the program on your hard drive with the name `hello.rust`.

=== Running the program

Open your console.
Switch to the directory you saved the program in, and type `cargo run`
You should see

----
Hello, world!
5 1.428571 1915.2
----

Congratulations!
You've written and run your first rust program!
